name: Test

on: push

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package.json') }}

      - name: Install Packages
        run: npm install

      - name: lint
        run: npm run lint

      - name: format
        run: npm run format:check

      - name: test
        run: npm run test
